param-grids:
  sink:
    - reg: 0.1
      maxiter: 100000
    - reg: 0.001
      maxiter: 100000
    - reg: 0.0001
      maxiter: 100000
  pdlp:
    - reg: 0.01
      maxiter: 500000
    - reg: 0.1
      maxiter: 500000
    - reg: 1.0
      maxiter: 500000
    - reg: 10.0
      maxiter: 500000
    - reg: 100.0
      maxiter: 500000
    - reg: 10000.0
      maxiter: 500000

solvers:
  sinkhorn:
    solver: uot.solvers.sinkhorn.SinkhornTwoMarginalSolver
    jit: true
    param-grid: sink

  pdlp:
    solver: uot.solvers.pdlp.PDLPSolver
    jit: true
    param-grid: pdlp

problems:
  dir: datasets/synthetic
  names:
    - 1D-cauchy-1024p
    - 1D-cauchy-2048p
    - 1D-cauchy-4096p
    - 1D-cauchy-8162p
    - 1D-cauchy-16324p
#    - 1D-cauchy-32768p


experiment:
  name: Measure Extensive
  function: uot.experiments.measurement.measure_with_gpu_tracker