param-grids:
  sink:
    - reg: 0.1
      maxiter: 100000
    - reg: 0.001
      maxiter: 500000
    - reg: 0.0001
      maxiter: 800000
  pdlp:
    - reg: 0.01
      maxiter: 1000000
    - reg: 0.1
      maxiter: 1000000
    - reg: 1.0
      maxiter: 1000000
    - reg: 10.0
      maxiter: 1000000
solvers:
  sinkhorn:
    solver: uot.solvers.sinkhorn.SinkhornTwoMarginalSolver
    jit: true
    param-grid: sink

  pdlp:
    solver: uot.solvers.pdlp.PDLPSolver
    jit: true
    param-grid: pdlp

problems:
  dir: datests/synthetic
  names:
    - 1D-cauchy-1024
    - 1D-cauchy-2048
    - 1D-cauchy-4096
    - 1D-cauchy-8192
    - 1D-cauchy-16384

experiment:
  name: Measure Cauchy
  function: uot.experiments.measurement.measure_time