param-grids:
  sink:
    - reg: 0.1
      maxiter: 100000
    - reg: 0.001
      maxiter: 100000
    - reg: 0.0001
      maxiter: 100000
  pdlp:
    - reg: 0.01
      maxiter: 500000
    - reg: 0.1
      maxiter: 500000
    - reg: 1.0
      maxiter: 500000
    - reg: 10.0
      maxiter: 500000
    - reg: 100.0
      maxiter: 500000
    - reg: 10000.0
      maxiter: 500000

solvers:
  sinkhorn:
    solver: uot.solvers.sinkhorn.SinkhornTwoMarginalSolver
    jit: true
    param-grid: sink

  pdlp:
    solver: uot.solvers.pdlp.PDLPSolver
    jit: true
    param-grid: pdlp

problems:
  dir: datasets/synthetic
  names:
    - 2D-gaussians-1c-64p
    - 2D-gaussians-2c-64p
    - 2D-gaussians-3c-64p
    - 2D-gaussians-1c-128p
    - 2D-gaussians-2c-128p
    - 2D-gaussians-1c-160p
    - 2D-gaussians-1c-192p
    - 2D-gaussians-3c-192p
    - 2D-gaussians-1c-256p


experiment:
  name: Measure Extensive
  function: uot.experiments.measurement.measure_with_gpu_tracker