param-grids:
  sink:
    - reg: 0.1
      maxiter: 100000
    - reg: 0.001
      maxiter: 100000
    - reg: 0.0001
      maxiter: 100000
  pdlp:
    - reg: 0.01
      maxiter: 500000
    - reg: 0.1
      maxiter: 500000
    - reg: 1.0
      maxiter: 500000
    - reg: 10.0
      maxiter: 500000
    - reg: 100.0
      maxiter: 500000
    - reg: 10000.0
      maxiter: 500000

solvers:
  sinkhorn:
    solver: uot.solvers.sinkhorn.SinkhornTwoMarginalSolver
    jit: true
    param-grid: sink

  pdlp:
    solver: uot.solvers.pdlp.PDLPSolver
    jit: true
    param-grid: pdlp

problems:
  dir: datasets/synthetic
  names:
    - 1D-gaussians-1c-1024p
    - 1D-gaussians-2c-1024p
    - 1D-gaussians-3c-1024p
    - 1D-gaussians-1c-2048p
    - 1D-gaussians-2c-2048p
    - 1D-gaussians-3c-2048p
    - 1D-gaussians-1c-4096p
    - 1D-gaussians-2c-4096p
    - 1D-gaussians-3c-4096p
    - 1D-gaussians-4c-4096p
    - 1D-gaussians-1c-8192p
    - 1D-gaussians-2c-8192p
    - 1D-gaussians-3c-8192p
    - 1D-gaussians-4c-8192p
    - 1D-gaussians-5c-8192p
    - 1D-gaussians-10c-8192p
    - 1D-gaussians-1c-16384p
    - 1D-gaussians-1c-32768p
    - 1D-gaussians-2c-16384p
    - 1D-gaussians-3c-16384p
    - 1D-gaussians-4c-16384p
    - 1D-gaussians-5c-16384p
    - 1D-gaussians-10c-16384p

experiment:
  name: Measure Extensive
  function: uot.experiments.measurement.measure_with_gpu_tracker