param-grids:
  lbfgs:
    - reg: 0.01
      maxiter: 30000
      tol: 0.000001
      # history_size: 10
      # line_search: zoom
      # maxls: 20

solvers:
  lbfgs:
    solver: uot.solvers.lbfgs.LBFGSTwoMarginalSolver
    jit: true
    param-grid: lbfgs
  lbfgs-pure:
    solver: uot.solvers.lbfgs.LBFGSPureSolver
    jit: true
    param-grid: lbfgs
  lbfgs-warmstart:
    solver: uot.solvers.lbfgs.WarmStartLBFGSTwoMarginalSolver
    jit: true
    param-grid: lbfgs

experiment:
  name: L-BFGS Two-Marginal OT Test
  function: uot.experiments.measurement.measure_with_gpu_tracker
