param-grids:
  sinkhorn:
    - reg: 0.01
      maxiter: 7000

solvers:
  sinkhorn:
    solver: uot.solvers.sinkhorn.SinkhornTwoMarginalSolver
    jit: true
    param-grid: sinkhorn

  sinkhorn-log:
    solver: uot.solvers.sinkhorn.SinkhornTwoMarginalLogJaxSolver
    jit: true
    param-grid: sinkhorn


experiment:
  name: Track Gen Reproducibility Across Sinkhorn Solvers
  function: uot.experiments.measurement.measure_with_gpu_tracker
