generators:
  _cauchy_defaults: &cauchy_defaults
    generator: uot.problems.generators.CauchyGenerator
    dim: 1
    num_datasets: 30
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-cauchy-1024p:
    <<: *cauchy_defaults
    n_points: 64
    borders: (-1, 1)

  1D-cauchy-2048p:
    <<: *cauchy_defaults
    n_points: 64
    borders: (-1, 1)

  1D-cauchy-4096p:
    <<: *cauchy_defaults
    n_points: 64
    borders: (-1, 1)

  1D-cauchy-8162p:
    <<: *cauchy_defaults
    n_points: 64
    borders: (-1, 1)

  1D-cauchy-16324p:
    <<: *cauchy_defaults
    n_points: 64
    borders: (-1, 1)