generators:
  _cauchy_defaults: &cauchy_defaults
    generator: uot.problems.generators.CauchyGenerator
    dim: 1
    num_datasets: 20
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-cauchy-1024p:
    <<: *cauchy_defaults
    n_points: 1024
    borders: (-1, 1)

  1D-cauchy-2048p:
    <<: *cauchy_defaults
    n_points: 2048
    borders: (-1, 1)

#  1D-cauchy-4096p:
#    <<: *cauchy_defaults
#    n_points: 4096
#    borders: (-1, 1)
#
#  1D-cauchy-8162p:
#    <<: *cauchy_defaults
#    n_points: 8162
#    borders: (-1, 1)
#
#  1D-cauchy-16324p:
#    <<: *cauchy_defaults
#    n_points: 16324  1D-cauchy-1024p:
#    <<: *cauchy_defaults
#    n_points: 1024
#    borders: (-1, 1)
#
#  1D-cauchy-2048p:
#    <<: *cauchy_defaults
#    n_points: 2048
#    borders: (-1, 1)
#
#  1D-cauchy-4096p:
#    <<: *cauchy_defaults
#    n_points: 4096
#    borders: (-1, 1)
#
#  1D-cauchy-8162p:
#    <<: *cauchy_defaults
#    n_points: 8162
#    borders: (-1, 1)
#
#  1D-cauchy-16324p:
#    <<: *cauchy_defaults
#    n_points: 16324
#    borders: (-1, 1)

#  1D-cauchy-32768p:
#    <<: *cauchy_defaults
#    n_points: 32768
#    borders: (-1, 1)
#    borders: (-1, 1)

  1D-cauchy-32768p:
    <<: *cauchy_defaults
    n_points: 32768
    borders: (-1, 1)