generators:
  _gaussian_defaults: &gauss_defaults
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    n_points: 64
    num_components: 1
    num_datasets: 10
    borders: (-10, 10)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: false
    seed: 42

  _cauchy_defaults: &cauchy_defaults
    generator: uot.problems.generators.CauchyGenerator
    dim: 1
    n_points: 64
    num_datasets: 30
    borders: (-10, 10)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: false
    seed: 42

  _exponential_defaults: &exp_defaults
    generator: uot.problems.generators.ExponentialGenerator
    dim: 1
    n_points: 64
    num_datasets: 30
    borders: (-10, 10)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: false
    seed: 42

  1D-gaussians-1c-1024p:
    <<: *gauss_defaults
    dim: 1
    n_points: 1024

  1D-gaussians-2c-1024p:
    <<: *gauss_defaults
    dim: 1
    n_points: 1024
    num_components: 2

  1D-gaussians-3c-1024p:
    <<: *gauss_defaults
    dim: 1
    n_points: 1024
    num_components: 3

  1D-gaussians-1c-2048p:
    <<: *gauss_defaults
    dim: 1
    n_points: 2048

  1D-gaussians-2c-2048p:
    <<: *gauss_defaults
    dim: 1
    n_points: 2048
    num_components: 2

  1D-gaussians-3c-2048p:
    <<: *gauss_defaults
    dim: 1
    n_points: 2048
    num_components: 3

  1D-gaussians-1c-4096p:
    <<: *gauss_defaults
    dim: 1
    n_points: 4096

  1D-gaussians-2c-4096p:
    <<: *gauss_defaults
    dim: 1
    n_points: 4096
    num_components: 2

  1D-gaussians-3c-4096p:
    <<: *gauss_defaults
    dim: 1
    n_points: 4096
    num_components: 3

  1D-gaussians-4c-4096p:
    <<: *gauss_defaults
    dim: 1
    n_points: 4096
    num_components: 4

  1D-gaussians-1c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192

  1D-gaussians-2c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192
    num_components: 2

  1D-gaussians-3c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192
    num_components: 3

  1D-gaussians-4c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192
    num_components: 4

  1D-gaussians-5c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192
    num_components: 5

  1D-gaussians-10c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192
    num_components: 10

  1D-gaussians-1c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384

  1D-gaussians-2c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384
    num_components: 2

  1D-gaussians-3c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384
    num_components: 3

  1D-gaussians-4c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384
    num_components: 4

  1D-gaussians-5c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384
    num_components: 5

  1D-gaussians-10c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384
    num_components: 10

  # ─── 2D mixtures ────────────────────────────────────────────────────────
  2D-gaussians-1c-64p:
    <<: *gauss_defaults
    dim: 2
    n_points: 64
    num_components: 1

  2D-gaussians-2c-64p:
    <<: *gauss_defaults
    dim: 2
    n_points: 64
    num_components: 2

  2D-gaussians-3c-64p:
    <<: *gauss_defaults
    dim: 2
    n_points: 64
    num_components: 3

  2D-gaussians-1c-128p:
    <<: *gauss_defaults
    dim: 2
    n_points: 128
    num_components: 1

  2D-gaussians-1c-160p:
    <<: *gauss_defaults
    dim: 2
    n_points: 160
    num_components: 1

  2D-gaussians-1c-192p:
    <<: *gauss_defaults
    dim: 2
    n_points: 192
    num_components: 1

  1D-cauchy-1024:
    <<: *cauchy_defaults
    n_points: 1024

  1D-cauchy-2048:
    <<: *cauchy_defaults
    n_points: 2048

  1D-cauchy-4096:
    <<: *cauchy_defaults
    n_points: 4096

  1D-cauchy-8162:
    <<: *cauchy_defaults
    n_points: 8192

  1D-cauchy-16324:
    <<: *cauchy_defaults
    n_points: 16384

  1D-exponential-1024:
    <<: *exp_defaults
    n_points: 1024

  1D-exponential-2048:
    <<: *exp_defaults
    n_points: 2048

  1D-exponential-4096:
    <<: *exp_defaults
    n_points: 4096

  1D-exponential-8162:
    <<: *exp_defaults
    n_points: 8192

  1D-exponential-16324:
    <<: *exp_defaults
    n_points: 16384