generators:
  _gauss_default: &gauss_default
    generator: uot.problems.generators.GaussianMixtureGenerator
    num_components: 1
    num_datasets: 12
    borders: (-6, 6)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: False
    seed: 52

  # 1D-gaussians-1c-16p:
  #   <<: *gauss_default
  #   dim: 1
  #   n_points: 16

  # 1D-gaussians-1c-32p:
  #   <<: *gauss_default
  #   dim: 1
  #   n_points: 32

  1D-gaussians-1c-64p:
    <<: *gauss_default
    dim: 1
    n_points: 64
